image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - dotnet build -c Release
    - dotnet run --project Koala.Tests/Koala.Tests.csproj -c Release -f netcoreapp2.1

deploy_job:
  stage: deploy
  #when: manual
  script:
    - ./ci.sh

  dependencies:
    - build_job
  